### PR TITLE
Inject symfony project root to php-airbrake configuration

### PR DESCRIPTION
**Pull request by aminin**

### CODE REVIEW

**Comment by eymengunay** [comment]
Hi @aminin, 

Is there a particular reason why you have re-added dev-master?

**Comment by aminin** [comment]
> Is there a particular reason why you have re-added dev-master?

I need `~1.1` for the project with `minimum-stability=stable`, and `dev-master` to test pull-requests like this and [that](https://github.com/dbtlr/php-airbrake/issues/48) together.

I see two solutions:

1. Bump version constraints at each release.
2. Set one constraint for both cases `<stable-constraint>||<dev-constraint>`.

**Comment by aminin** [comment]
Would you please make a tag?

**Comment by YatkinK** [comment]
:+1:

**Pull request closed without merging**
